one_wire:
  platform: gpio
  pin: $one_wire_pin

sensor:
  - platform: dallas_temp
    address: $fridge_temp_address
    update_interval: 1s
    name: "Fridge Temperature" 
    id: fridge_temp
    accuracy_decimals: 5

  - platform: dallas_temp
    address: $beer_temp_address
    update_interval: 1s    
    name: "Beer Temperature" 
    id: beer_temp
    accuracy_decimals: 5

  # SLOW FILTERS:
  # - Apply heavy smoothing to eliminate noise
  # - Essential for reliable peak detection
  # - Used for PID control to prevent oscillation
  # - Help system distinguish real trends from noise

  - platform: copy 
    source_id: fridge_temp
    id: fridge_temp_slow
    name: Fridge Temperature Slow
    accuracy_decimals: 2  
    filters: 
      - filter_out: 85.0  # Filter out the DS18B20 error value
      - filter_out: nan
      - clamp:
          min_value: -20
          max_value: 75
          ignore_out_of_range: true      
      - exponential_moving_average:
          alpha: $fridge_slow_alpha
          send_every: 1
    
  - platform: copy 
    source_id: beer_temp
    id: beer_temp_slow
    name: Beer Temperature Slow  
    accuracy_decimals: 2
    filters:
      - filter_out: 85.0  # Filter out the DS18B20 error value
      - filter_out: nan
      - clamp:
          min_value: -20
          max_value: 75
          ignore_out_of_range: true       
      - exponential_moving_average:
          alpha: $beer_slow_alpha
          send_every: 1          